- lib/lldbwrap.sh
Just a heads up, this plugin is broken on Darwin right now. This was the first thing I noticed.
> Add a condtional check to avoid calling `readlink -f` on Darwin

- doc/nvimgdb.txt
There is a typo which causes an error when running helptags.
> Fix label for docs of GdbStartPDB

- lib/lldb_commands.py
lib/lldb_commands.py:_GetBreaks iterates over all found breakpoints
and checks the filename of it. However, lldb will set breakpoints in
targets with symbol information but no sources and thus the code
tries to call functions on `None`.
Break out of the inner loop if there is no filename corresponding to
the breakpoint
> Don't send breakpoints from lldb_command for symbols without sources

- autoload/nvimgdb.vim
Changed the function GdbKill() for compatibility reasons with "set hidden" .vimrc option.
issue #48 can be closed
> Changed GdbKill() for 'set hidden' compatibility

- rplugin/python3/gdb/win.py
neovim offers a more direct API to perform many actions rather than
using ex commands. Implementing this removes, in this case, around 10
lines and provides a cleaner and more efficient solution.
> Reimplement win.jump with nvim API functions

- rplugin/python3/gdb/app.py
- rplugin/python3/gdb/config.py
Scrolloff has clumsy behavior at times while using the neovim terminal
emulator. Allow it to be disabled with the default behavior to use
the previous `setlocal scrolloff=5` behavior.
> Add an option to disable the usage of scrolloff

- doc/nvimgdb.txt
- rplugin/python3/gdb/app.py
- rplugin/python3/gdb/scm.py
- rplugin/python3/gdb/win.py
I used nvim's virtual text feature to show the values of local variables inline in the buffer (if you're interested, I can do a PR but I only have lldb support). But for that I needed more autocmds.
> Add more autocmds

- rplugin/python3/gdb/app.py
- rplugin/python3/gdb/backend/bashdb.py
- rplugin/python3/gdb/backend/gdb.py
- rplugin/python3/gdb/backend/lldb.py
- rplugin/python3/gdb/backend/pdb.py
Debugging nvim-gdb can be quite confusing given that you can't actually
attach a debugger to it since it runs as part of the neovim runtime.
Implicit runtime behavior makes it more difficult. This patch simply
changes one specific behavior to be more explicit.
> Explicitly initialize individual backends instead of relying on importlib and implicit behavior

- lib/lldb_wrap.sh
- rplugin/python3/gdb/__init__.py
lldb emits colorized text via standard ansi escape sequences e.g.
\033[31mColored text\033[0mNon-colored text.
This patch adds a parser that strips these sequences on all text piped
from neovim's terminal to gdb so that the user can have colorized text
> Add a regex to remove ansi color in the parser and enable color in lldb

- lib/lldb_commands.py
- lib/lldb_wrap.sh
- rplugin/python3/gdb/backend/lldb.py
You can use `debugger.GetID()` to uniquely identify a debugger and
`lldb.SBDebugger_FindDebuggerWithID(id)` to get it later in a different
context. This allows us to restore the old implementation.
This is ideal because the current lldb proxy doesn't correctly handle
input all the time. Isolating the exact issue is difficult, but many
keys entries can trigger an erasure of the entire line as well as
frequent clobbering of history.
> revert back to the old lldb implementation

- rplugin/python3/gdb/client.py
Note that the terminal buffer doesn't provide a filetype, it would be better to set the filetype of debug buffer to 'nvimgdb'. This option allows user to customize the style of the debug window using `autocmd FileType nvimgdb` or `ftplugin/nvimgdb.vim`.
> Set buffer filetype to 'nvimgdb'

- lua/nvimgdb/win.lua
See `:h zv`. I made the change in the lua branch because that's what I am using. Should be easy to backport.
> handle folding with zv

- lua/nvimgdb/app.lua
This avoids triggering mappings etc for unrelated terminals in the same tab.
Maybe the string 'nvimgdb' should be a constant somewhere.
> use nvimgdb filetype instead of terminal

- doc/nvimgdb.txt
- lua/nvimgdb/app.lua
- lua/nvimgdb/config.lua
Personally, I find this behavior annoying. I left it on by default, but when missing from the config it is set to false.
> Allow configuring jumping to bottom of gdb buffer

- rplugin/python3/gdb/backend/gdb.py
Fixed: Editor is out sync with Breakpoint hits - cursor is not auto positioned to hit line.
Breakpoint hit may not start with new line as on example:
Thread 1 "wrc_proc_test1" hit Breakpoint 2
Added support of gdb temp breakpoints
gdb version 9.2
> Editor is out sync with GDB Breakpoint hits - cursor is not positioned to hit line

- lib/gdb_wrap.sh
Press `<c-p>` sometimes make the prompt broken, I don't know why until I `set prompt \033[34mgdb \033[0m` in `.gdbinit` and run gdb without nvim-gdb also found this issue.
And then someone provides me below information, I change `set prompt \001\033[34m\002gdb \001\033[0m\002` to solve 
this issue successfully in native gdb.
It looks like also works with `prompt.hook`.
I'm not sure this works on macOS, I only test on Linux, BTW, the tests are hung.....
FYI: 
https://stackoverflow.com/questions/9468435/how-to-fix-column-calculation-in-python-readline-if-using-color-prompt/9468954#9468954
> fix(gdb_wrap): make prompt.hook keep original position

- lua/nvimgdb/win.lua
Some gdb's instructions will fire jump win action which will jump between the code window and the term window.
It's unnecessary to fire redundant WinEnter event which makes the status line Dithering.
> fix(win.lua): avoid unnecessary WinEnter event

- lua/nvimgdb.lua
- lua/nvimgdb/win.lua
Without recording after jumping window, buffer may not be cleaned. (keymaps)
> fix(win.lua): should unset keymap for buffer after nvim-gdb is closed

- lua/nvimgdb/win.lua
- test/test_10_generic.py
Remove redundant win_getid(nvim_win_get_number(win_handle))
> refactor(win): nvim_get_current_win is already a window handle

- lua/nvimgdb/app.lua
The way insert mode is currently entered doesn't work well if `nvim` is already configured to enter insert mode on `TermOpen`.
(for example if you have `autocmd TermOpen * startinsert` in your vim init script)
If the terminal starts already in insert mode then the `vim.fn.feedkeys("i")` will feed the 'i' character to the gdb/lldb command prompt (that is an invalid command).
Using `vim.cmd("startinsert")` doesn't trigger the problem:
- If we are not in insert mode then insert mode is entered
- If we are already in insert mode then nothing happens
> Better way to enter insert mode

- lib/rr-replay.py
`rr replay` is launched via a helper script written in Python.
This script must be run by Python v3; it is not compatible with
Python v2. Use `python3` in the shebang line so that `python2`
isn't called on systems where `python` is a link to `python2`.
See Python PEP 394.
> rr replay: ensure helper script runs in python3

- lua/nvimgdb/app.lua
- lua/nvimgdb/keymaps.lua
Wraps buf_del_keymap in pcall(), fixing #185 .
> fix(185): Wrap buf_del_keymap in pcall()

- lib/gdb_wrap.sh
- lib/lldb_wrap.sh
- test/all.sh
On some platforms, like termux on android, `/tmp` is inaccessible. If we remove the `/tmp` prefix on the templates and instead set the `--tmpdir` flag, `mktemp` will use `$TMPDIR`, which on termux is set to `/data/data/com.termux/files/usr/tmp`
On my debian box where `TMPDIR` is unset it falls back to `/tmp`.
From the manpage:
```
> -p DIR, --tmpdir[=DIR]
>   interpret TEMPLATE relative to DIR; if DIR is not specified, use
>   $TMPDIR if set, else /tmp.
```
BTW, the code that handles this is here: http://git.savannah.gnu.org/cgit/coreutils.git/tree/src/mktemp.c#n286
> Don't force temp files to be created in /tmp

- lib/gdb_commands.py
This change gives us paths after path substitution in gdb. With that we're able to jump to correct symbols more often in nvim. Especially when debugging code from system libraries.
> Use full, resolved paths from gdb

- lib/gdb_commands.py
- test/10_generic_spec.lua
- test/all.py
- utils/testenv_darwin.py
When encountered <MULTIPLE> breakpoint in gdb output  as following, parser will not consider Ena as "y".
```
Num     Type           Disp Enb Address            What
1       breakpoint     keep y   <MULTIPLE>         
1.1                         y   0xffff800080d90414 in __arch_counter_get_cntvct at ./arch/arm64/include/asm/arch_timer.h:204
1.2                         y   0xffff800081014f10 in __arch_counter_get_cntvct at ./arch/arm64/include/asm/arch_timer.h:204
```
> Fix older gdb breakpoints parse bugs

- lib/gdb_commands.py
Thanks for the awesome project!
I tried using it for ESP32 debugging which uses its own gdb fork but it didn't work out of the box.
```
xtensa-esp32s3-elf-gdb --version
GNU gdb (crosstool-NG esp-2021r2-patch5) 9.2.90.20200913-git
```
Apparently this gdb version uses python2.7 and complains about some python3 specific syntax.
This PR removes python3 specific code to make gdb_commands.py compatible with python2.7.
It woks fine with ESP32-S3 gdb:
```
:GdbStart xtensa-esp32s3-elf-gdb -x gdbinit .pio/build/esp32-s3-zero/firmware.elf
```
I only tested it with ESP32-S3 and a native gdb 15.1 on arch linux.
> Support older GDB versions which use python2.7

- lib/rr-replay.py
Notice that the `GdbStartRR` was not working, so I fixed it. But it appears it have stopped working just in the last version (https://github.com/rr-debugger/rr/commit/07d2aeb7e7a7e9b632681107f4f75602a5362060), so I am not sure if you would like to break support from all previous versions to address this.
I don't have time to make a more generalized fix, but here is with a have done.
> Update rr-replay.py to work with rr 5.8.0

- doc/nvimgdb.txt
- lua/nvimgdb/backend/gdb.lua
- lua/nvimgdb/backend/lldb.lua
cargo-debug is the utility to start gdb/lldb with Rust porjects. To make
it work with nvim-gdb, just pass the init commands through
'--command-file' argument to the 'cargo debug'.
> Support cargo-debug

- lib/gdb_commands.py
- lua/nvimgdb/backend/gdb.lua
Currently (using gdb), typing a command like `p foo` will cause the program to jump to the source even thought the program hasn't progressed so it will jump to the same place each time. This is annoying when you want to print out a series of variable and you keep being taken out of the gdb terminal.
This PR stops this occurring by recording the previous filename + line we jumped to and only jumping if we are jumping somewhere else.
I have only implemented this for GDB (since it'' the only debugger I use). If there is interest in this PR, I can implement for the others.
> Don't jump to source after commands that don't progress the program
